name: Error Handling, Retry Mechanisms, and Notifications

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Make the flaky script executable
      - name: Set execute permission for flaky-script.sh
        run: chmod +x flaky-script.sh

      # Step 2: Flaky step with retry logic
      - name: Run flaky step with retry
        run: |
          for i in {1..3}; do
            echo "Attempt $i: Running flaky script..."
            if ./flaky-script.sh; then
              echo "Script succeeded on attempt $i"
              break
            elif [ $i -eq 3 ]; then
              echo "Script failed after 3 attempts" >&2
              exit 1
            fi
            sleep 5
          done
        continue-on-error: false # Even if this step fails, the workflow will continue

      # # Step 3: Simulate a failure
      # - name: Simulate failure
      #   run: exit 1
      #   continue-on-error: true # Simulated step failure for testing

      # # Step 4: Log a warning on failure
      # - name: Log failure
      #   if: failure()
      #   run: echo "One or more steps failed!"

      # Step 5: Send email notification on failure
      - name: Send Email Notification
        if: failure() # Executes only if the workflow fails
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com   # Replace with Actual email provider's SMTP server
          server_port: 587                # Replace with Actual provider's SMTP port
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 GitHub Workflow Failed"
          body: |
            Hello,
            The workflow **${{ github.workflow }}** failed on job **${{ github.job }}** in branch **${{ github.ref_name }}**.
            Please check the logs for more details.
          to: "sangappa.biraj@hcltech.com"
          from: ${{ secrets.EMAIL_USERNAME }}

      # Step 6: Success message
      - name: Workflow Succeeded
        if: success()
        run: echo "Workflow completed successfully!"
